version: '3'
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./:/var/lib/mysql
  backend:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV:prod
    depends_on:
      - db
    volumes:
      - ./app/:/mnt/app/
